traces:
  configs:
  - name: default
    receivers:
      otlp:
        protocols:
          grpc:
      # jaeger:
      #   protocols:
      #     grpc: # listens on the default jaeger grpc port: 14250
    remote_write:
      - endpoint: tempo:55680 #Tempo server otlp grpc
        # endpoint: tempo-us-central1.grafana.net:443
        insecure: true  # only add this if TLS is not required
        # queue:
        #   retry_on_failure: true
    # batch:
    #   timeout: 5s
    #   send_batch_size: 100