apiVersion: 1

# deleteDatasources:
#   - name: Tempo

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        tags:
          - service_name
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: traceID=(\w+)
          name: TraceID
          url: $${__value.raw}
